backends:
  arvan:
    type: s3
    path: s3.ir-thr-at1.arvanstorage.ir/restic-backup-confluenceb
    key: FtY4refjvQYnBtgMhAG8SqjxVRfWnuj0nMvvpWfQksli5IAWymeLB9XHMG8LKOyMskFODc7Ckj0qPe3Kic1A
    env:
      AWS_ACCESS_KEY_ID: 9892ae11-6a41-4276-b66e-bfb6acb62f4e
      AWS_SECRET_ACCESS_KEY: 8c6fa042f0c518d0b1e5af9a97fad81965f2e965e1fce3d9ca549d684fb0369b
    rest:
      user: ""
      password: ""
    options: {}
locations:
  confluence:
    from:
    - confluence-home
    type: volume
    to:
    - arvan
    hooks:
      dir: ""
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    forgetoption: {}
    copyoption: {}
version: 2
