#https://github.com/teamatldocker/jira
#ava -jar /var/atlassian/jira/atlassian-agent.jar  -p jira -m u3q3@yahoo.com -n hr -o jira.paraf.com -s B6SQ-RAXI-T7WM-H3L1
#java -jar /var/atlassian/jira/atlassian-agent.jar  -p is.origo.jira.tempo-plugin -m u3q3@yahoo.com -n hr -o jira.paraf.com -s B6SQ-RAXI-T7WM-H3L1
#java -jar /var/atlassian/jira/atlassian-agent.jar  -p com.allenta.jira.plugins.gitlab.gitlab-listener -m u3q3@yahoo.com -n hr -o jira.paraf.com -s B6SQ-RAXI-T7WM-H3L1


version: '3'

services:
  jira:
    container_name: jira
    # user: "${UID}:${GID}"
    #export UID=$(id -u)
    #export GID=$(id -g)
    user: 1000:1000
    depends_on:
      - postgresql
    image: teamatldocker/jira:8.17.0
    networks:
       jiranet:
        #  ipv4_address: 172.21.0.3
       publish_network:
    volumes:
      - jira-data:/var/atlassian/jira
      - jira-bin:/opt/jira/bin
      - ./atlassian-agent.jar:/var/atlassian/jira/atlassian-agent.jar
      # #backup
      # - backup_jira:/var/atlassian/jira/export:rw
    # ports:
    #   - '6543:8080'
    # command: tail -f /dev/null
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
      - 'JIRA_DB_PASSWORD=jellyfddfgdish'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME=jira.parafacc.ir'
      - 'JIRA_PROXY_PORT=443'
      - 'JIRA_PROXY_SCHEME=https'
    # command: echo 'export CATALINA_OPTS="-javaagent:/var/atlassian/jira/atlassian-agent.jar ${CATALINA_OPTS}"' >> /opt/jira/bin/setenv.sh
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      - traefik.enable=true
      - traefik.docker.network=publish_network
      - traefik.http.services.jira.loadbalancer.server.port=8080
      - traefik.http.routers.jira.rule=Host(`jira.parafacc.ir`)
      - traefik.http.routers.jira.service=jira
      - traefik.http.routers.jira.entrypoints=websecure
      - traefik.http.routers.jira.tls.certresolver=letsencrypt

  postgresql:
    container_name: postgresql
    image: postgres:9.5-alpine
    ports:
      - '0.0.0.0:65432:5432'
    networks:
      - jiranet
    volumes:
      - jira-postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jellyfddfgdish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

networks:
  jiranet:
    driver: bridge
    name: jira_jiranet
  publish_network:
    external: true
volumes:
  jira-bin:
    name: jira-bin
  jira-data:
    name: jira-data
  jira-postgresqldata:
    name: jira-postgresqldata
  # backup_jira:
  #    name: backup_jira
     

